
<field:fx itemname="房型" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:fx>

<field:dd itemname="到店" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dd>

<field:ld itemname="离店" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ld>

<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>
