<div class="f14464843411">
      <ul class="f14464843415">
      <li class="f14464843416">
          <div class="f14464843419"> <a class="f144648434110" href="[field:arcurl/]">[field:title/]</a> <span class="f144648434111">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> </div>
      </li>
      <li class="news_c">[field:description function="cn_substr(@me,600)"/]...</li>
       </ul>       
    </div>