<li class="f14453721557">
          <div class="f14453721569">
            <div class="f14453721558"><a class="f14453721559" href="[field:arcurl/]"><img class="f14453721560" src="[field:picname/]" /></a></div>
            <div class="f14453721561"> <a class="f14453721562" href="[field:arcurl/]">[field:title/]</a>
              <!-- <div class="f14453721563"><span class="f14453721564">原价：5000.00元/人</span><span class="f14453721565">现价：1500.00元/人</span></div> -->
              <div class="f14453721566">[field:description function="cn_substr(@me,100)"/]...</div>
              <div class="f14453721567"><a class="f14453721568" href="[field:arcurl/]">查看更多</a></div>
            </div>
          </div>
        </li>