<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,366);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",406,458);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2048,2083);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2120,2155);
$z[5][4]['filename']="left.htm";
$z[6]=Array("type","\r\n      <div class=\"f14453721553\">\r\n        [field:typename/]      </div>\r\n",2302,2400);
$z[7]=Array("field","",2543,2572);
$z[7][4]['name']="position";
$z[8]=Array("field","",2719,2738);
$z[8][4]['name']="title";
$z[9]=Array("field","",2793,2849);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",3424,3442);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",3492,3517);
$z[11][4]['get']="pre";
$z[12]=Array("global","",3618,3645);
$z[12][4]['name']="cfg_basehost";
$z[13]=Array("include","",3705,3742);
$z[13][4]['filename']="footer.htm";

?>