<li class="f14457532177">
          <div class="f14457532178"><a class="f14457532179" href="[field:arcurl/]"><img class="f14457532180" src="[field:picname/]" /></a></div>
          <div class="f14457532181"> <a class="f14457532182" href="[field:arcurl/]">[field:title/]</a>
          <div class="f14457532183">[field:description function="cn_substr(@me,80)"/]...</div>
          <a class="f14457532184" href="[field:arcurl/]">查看</a>
           </div>
        </li>