<?php
$z[0]=Array("global","",137,159);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("channel","\r\n        <li class=\"buqpywfVSf\">\r\n      <a class=\"BY5maaxCdj\" href=\"[field:typelink/]\">[field:typename/]</a>\r\n    </li>\r\n",2219,2414);
$z[1][4]['row']="8";
$z[1][4]['type']="top";
$z[2]=Array("global","",3728,3750);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",3773,3795);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",3817,3839);
$z[4][4]['name']="cfg_add";
$z[5]=Array("global","",3863,3889);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",3963,3987);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",4079,4106);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",4159,4186);
$z[8][4]['name']="cfg_basehost";

?>