<?php
$z[0]=Array("global","",188,211);
$z[0][4]['name']="cfg_logo";
$z[1]=Array("global","",276,298);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("arclist","\r\n                    <li class=\"CgZXEuYqQX\">\r\n            <div class=\"vzPMgdTCUL\"><a class=\"HbrNEB75qk\" href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n            <div class=\"PJ3I80pZ1K\">[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</div>\r\n          </li>\r\n",1393,1746);
$z[2][4]['row']="8";
$z[2][4]['orderby']="pubdate";
$z[2][4]['typeid']="4";
$z[3]=Array("global","",2014,2039);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li class=\"f14478962933\" onclick=\"javascript:window.open('[field:typelink/]','_self')\">\r\n     <a class=\"f14478962934\" href=\"[field:typelink/]\">[field:typename/]</a>\r\n    </li>\r\n",2601,2861);
$z[4][4]['row']="8";
$z[4][4]['type']="top";

?>