<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,472);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2062,2097);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2131,2166);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",2349,2372);
$z[6][4]['name']="seotitle";
$z[7]=Array("field","",2525,2554);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                <li class=\"f14464843416\">\r\n          <div class=\"f14464843419\"> <a class=\"f144648434110\" href=\"[field:arcurl/]\">[field:title/]</a> <span class=\"f144648434111\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n        </li>\r\n",2696,2989);
$z[8][4]['pagesize']="10";
$z[9]=Array("include","",3054,3091);
$z[9][4]['filename']="footer.htm";

?>