<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,472);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2064,2099);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2133,2168);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",2352,2375);
$z[6][4]['name']="seotitle";
$z[7]=Array("field","",2528,2557);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                <li class=\"f14464848057\">\r\n          <div class=\"f14464848058\">\r\n          <a class=\"f14464848059\" href=\"[field:arcurl/]\">\r\n          <img class=\"f144361829613\" src=\"/image/ioc21.png\" />\r\n          <img class=\"f144648480510\" src=\"[field:picname/]\" /></a></div>\r\n          <div class=\"f144648480511\"> <a class=\"f144648480512\" href=\"[field:arcurl/]\">[field:title/]</a> </div>\r\n        </li>\r\n",2693,3138);
$z[8][4]['pagesize']="9";
$z[9]=Array("include","",3203,3240);
$z[9][4]['filename']="footer.htm";

?>