<?php
$z[0]=Array("include","",2282,2317);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",2349,2384);
$z[1][4]['filename']="left.htm";
$z[2]=Array("field","",2573,2596);
$z[2][4]['name']="seotitle";
$z[3]=Array("field","",2749,2778);
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n    <div class=\"f14464843411\">\r\n      <ul class=\"f14464843415\">\r\n      <li class=\"f14464843416\">\r\n          <div class=\"f14464843419\"> <a class=\"f144648434110\" href=\"[field:arcurl/]\">[field:title/]</a> <span class=\"f144648434111\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n      </li>\r\n      <li class=\"news_c\">[field:description function=\"cn_substr(@me,600)\"/]...</li>\r\n       </ul>       \r\n    </div>\r\n",2847,3311);
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",3410,3487);
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="3";

?>