<?php
$z[0]=Array("global","",267,293);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",334,363);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",403,461);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",2051,2086);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",2118,2153);
$z[4][4]['filename']="left.htm";
$z[5]=Array("list","\r\n                    <li class=\"f14466174189\">\r\n            <div class=\"f144661741810\"><a class=\"f144661741811\" href=\"[field:arcurl/]\"><img class=\"f144661741860\" src=\"[field:picname/]\" /></a></div>\r\n            <div class=\"f144661741861\"> <a class=\"f144661741862\" href=\"[field:arcurl/]\">[field:title/]</a> </div>\r\n          </li>\r\n",2734,3101);
$z[5][4]['perpage']="9";
$z[6]=Array("pagelist","",3259,3288);
$z[6][4]['listsize']="4";
$z[7]=Array("include","",3346,3383);
$z[7][4]['filename']="footer.htm";

?>